import data3 from '../PrimaryInformation/ApplyInformationLocatorsandData.json'
class Applicant_Info{
    Applicant_Info(){

        cy.reload(true)
        cy.wait(2000)
        cy.get(data3.radioButton).check('6', {force:true}).should('be.checked')
        cy.wait(2000)
        cy.xpath(data3.Study_Type).click()
        cy.wait(2000)
        cy.get(data3.type_select).contains('Home',{force: true}).click()
        cy.wait(2000)
        cy.xpath(data3.name_bn).type('নাফিজ চৌধুরী')
        cy.wait(2000)
        cy.xpath(data3.father_name_en).should('be.visible').type('Shorif Khan')
        cy.wait(2000)
        cy.xpath(data3.father_name_bn).should('be.visible').type('শরিফ খান')
        cy.wait(2000)
        cy.xpath(data3.mother_name_en).should('be.visible').type('Ani Chowdhury')
        cy.wait(2000)
        cy.xpath(data3.mother_name_bn).should('be.visible').type('আনি চৌধুরী')
        cy.wait(2000)
        cy.get(data3.gender).click()
        cy.wait(2000)
        cy.get(data3.gender_select).contains('Male',{force: true}).click()
        cy.wait(2000)
        cy.get(data3.nid).should('be.visible').type('2323454565')
        cy.wait(2000)
        cy.get(data3.marital_status).click()
        cy.wait(2000)
        cy.get(data3.marital_status_choose).contains('Single', {force: true}).click()
        cy.wait(2000)
        cy.get(data3.present_status).click()
        cy.wait(2000)
        cy.get(data3.present_status_choose).contains('Student', {force: true}).click()
        cy.wait(2000)
        cy.screenshot()
    }
} export default Applicant_Info